name: Experiment Results
description: Share and discuss experiment results related to the project.
labels: ["experiment", "results"]
body:
  - type: checkboxes
    id: no-duplicate-experiment
    attributes:
      label: "⚠️ Please check that similar experiment results haven't been shared already."
      description: "This helps us avoid redundancy and keeps experiment records organized."
      options:
        - label: "이전에 공유된 [실험 결과](https://github.com/your-repo/issues?q=is%3Aissue+is%3Aopen+label%3Aexperiment) 중 중복되는 것이 없습니다."
          required: true

  - type: input
    id: experiment-title
    validations:
      required: true
    attributes:
      label: "🔬 실험 제목"
      description: "실험의 간단한 제목을 입력해주세요."
      placeholder: "예: 데이터 증강 효과 검증 실험"

  - type: textarea
    id: experiment-summary
    validations:
      required: true
    attributes:
      label: "📊 실험 요약"
      description: "실험의 주요 결과와 결론을 간략히 요약해주세요."
      placeholder: "예: 데이터 증강을 통해 정확도가 3% 상승하였음..."

  - type: textarea
    id: key-observations
    validations:
      required: false
    attributes:
      label: "🔍 주요 관찰 내용"
      description: "실험 중에 특히 눈에 띄었던 점이나 흥미로운 발견이 있다면 공유해주세요."
      placeholder: "예: 특정 데이터 증강 기법에서 성능 저하가 관찰됨..."

  - type: textarea
    id: next-steps
    validations:
      required: false
    attributes:
      label: "➡️ 다음 단계 제안"
      description: "이 실험에 기반하여 제안할 수 있는 다음 실험이나 개선 사항이 있으면 작성해주세요."
      placeholder: "예: 증강 기법 조합을 달리하여 추가 실험 필요."

  - type: dropdown
    id: result-significance
    attributes:
      label: "⭐ 결과 중요도"
      description: "이번 실험 결과가 프로젝트에 얼마나 중요한지 설정해주세요."
      options:
        - Low
        - Medium
        - High
