name: New Feature Request
description: Suggest a new feature or enhancement for the project.
labels: ["feature", "enhancement"]
body:
  - type: input
    id: feature-title
    validations:
      required: true
    attributes:
      label: "💡 기능 제목"
      description: "추가하고 싶은 기능의 간단한 제목을 입력해주세요."
      placeholder: "예: 사용자 로그인 기능"

  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "📄 기능 설명"
      description: "제안하는 기능의 목적과 세부 내용을 설명해주세요."
      placeholder: "예: 사용자가 개인 계정을 생성하고 로그인할 수 있도록 하기 위해 사용자 인증 기능을 추가하고자 합니다."

  - type: textarea
    id: feature-benefits
    validations:
      required: true
    attributes:
      label: "🎯 기능 도입의 이점"
      description: "이 기능이 프로젝트에 어떤 이점을 줄 수 있는지 설명해주세요."
      placeholder: "예: 로그인 기능을 통해 사용자 맞춤 설정이 가능해져서 사용자 경험이 향상됩니다."

  - type: textarea
    id: potential-issues
    validations:
      required: false
    attributes:
      label: "⚠️ 잠재적 문제"
      description: "이 기능 도입 시 발생할 수 있는 잠재적 문제나 어려움이 있다면 적어주세요."
      placeholder: "예: 로그인 기능 추가 시 데이터 보안 및 개인 정보 보호 고려 필요."

  - type: textarea
    id: related-features
    validations:
      required: false
    attributes:
      label: "🔗 관련 기능"
      description: "이 기능과 관련된 이전 기능 요청이나 이슈가 있다면 이슈 번호를 간단히 언급해주세요."
      placeholder: "예: 관련 기능 요청 - #23, close #24"
